/* eslint-disable @typescript-eslint/no-var-requires */
/* Auto-generated by scripts/prepare-ffw2024-assets.mjs — do not edit manually */

const FFW2024_IMAGE_MAP: Record<string, string> = {
  'public/images/2024/clock.png': require('./img/2024/clock.webp') as string,
  'public/images/2024/Frame-dd.png': require('./img/2024/Frame-dd.webp') as string,
  'public/images/2024/Highlights/highlight-1.jpg': require('./img/2024/Highlights/highlight-1.webp') as string,
  'public/images/2024/Highlights/highlight-2.jpg': require('./img/2024/Highlights/highlight-2.webp') as string,
  'public/images/2024/Highlights/highlight-3.jpg': require('./img/2024/Highlights/highlight-3.webp') as string,
  'public/images/2024/LF Carnival gif carousel x2.gif': require('./img/2024/LF Carnival gif carousel x2.gif') as string,
  'public/images/2024/location.png': require('./img/2024/location.webp') as string,
  'public/images/2024/logo.png': require('./img/2024/logo.webp') as string,
  'public/images/2024/play-icon.png': require('./img/2024/play-icon.webp') as string,
  'public/images/2024/see-it.png': require('./img/2024/see-it.png') as string
};

/** Resolve classic `public/images/...` path to bundled WebP (or GIF) URL. */
export function resolveFfw2024Image(classicPath: string): string {
  const normalized = classicPath.replace(/\\/g, '/');
  const url = FFW2024_IMAGE_MAP[normalized];

  if (!url) {
    console.warn('[Ffw2024] Missing bundled image for:', normalized);
    return normalized;
  }

  return url;
}
