/* eslint-disable @typescript-eslint/no-var-requires */
/* Auto-generated by scripts/prepare-ffw2023-assets.mjs — do not edit manually */

const FFW2023_IMAGE_MAP: Record<string, string> = {
  'public/images/10Jul/image-1.png': require('./img/10Jul/image-1.webp') as string,
  'public/images/10Jul/image-2.png': require('./img/10Jul/image-2.webp') as string,
  'public/images/10Jul/image-3.png': require('./img/10Jul/image-3.webp') as string,
  'public/images/10Jul/image-4.png': require('./img/10Jul/image-4.webp') as string,
  'public/images/17Jul/image-1.png': require('./img/17Jul/image-1.webp') as string,
  'public/images/17Jul/image-2.png': require('./img/17Jul/image-2.webp') as string,
  'public/images/17Jul/image-3.png': require('./img/17Jul/image-3.webp') as string,
  'public/images/17Jul/image-4.png': require('./img/17Jul/image-4.webp') as string,
  'public/images/4july/DKOH.jpg': require('./img/4july/DKOH.webp') as string,
  'public/images/4july/ER.png': require('./img/4july/ER.webp') as string,
  'public/images/4july/image-2.png': require('./img/4july/image-2.webp') as string,
  'public/images/4july/image-3.png': require('./img/4july/image-3.webp') as string,
  'public/images/4july/image-4.png': require('./img/4july/image-4.webp') as string,
  'public/images/4july/Keynote-Address-1.png': require('./img/4july/Keynote-Address-1.webp') as string,
  'public/images/about-bg.png': require('./img/about-bg.webp') as string,
  'public/images/banner-text.png': require('./img/banner-text.webp') as string,
  'public/images/banner.png': require('./img/banner.webp') as string,
  'public/images/Brand Badge_DBS-Left_E_RGB.png': require('./img/Brand Badge_DBS-Left_E_RGB.webp') as string,
  'public/images/btn_calendar_inactive.png': require('./img/btn_calendar_inactive.webp') as string,
  'public/images/btn_calendar.png': require('./img/btn_calendar.webp') as string,
  'public/images/btn_playback.png': require('./img/btn_playback.webp') as string,
  'public/images/btn_watch_inactive.png': require('./img/btn_watch_inactive.webp') as string,
  'public/images/btn_watch.png': require('./img/btn_watch.webp') as string,
  'public/images/dropdown.png': require('./img/dropdown.webp') as string,
  'public/images/duotone-stripe.png': require('./img/duotone-stripe.webp') as string,
  'public/images/gallery/China FFW 5 - Running.jpg': require('./img/gallery/China FFW 5 - Running.webp') as string,
  'public/images/gallery/FFW19_072.jpg': require('./img/gallery/FFW19_072.webp') as string,
  'public/images/gallery/FFW19_299.jpg': require('./img/gallery/FFW19_299.webp') as string,
  'public/images/gallery/Hong Kong FFW 5.jpg': require('./img/gallery/Hong Kong FFW 5.webp') as string,
  'public/images/gallery/India FFW 7.jpg': require('./img/gallery/India FFW 7.webp') as string,
  'public/images/gallery/Indo FFW 1.jpg': require('./img/gallery/Indo FFW 1.webp') as string,
  'public/images/gameshow/CN.png': require('./img/gameshow/CN.webp') as string,
  'public/images/gameshow/HK.jpg': require('./img/gameshow/HK.webp') as string,
  'public/images/gameshow/ID.png': require('./img/gameshow/ID.webp') as string,
  'public/images/gameshow/RKL_0416.jpg': require('./img/gameshow/RKL_0416.webp') as string,
  'public/images/gameshow/SG_NEW.jpg': require('./img/gameshow/SG_NEW.webp') as string,
  'public/images/gameshow/TW.JPG': require('./img/gameshow/TW.webp') as string,
  'public/images/highligh-1.png': require('./img/highligh-1.webp') as string,
  'public/images/highlight-1.png': require('./img/highlight-1.webp') as string,
  'public/images/highlight-2.png': require('./img/highlight-2.webp') as string,
  'public/images/highlight-3.png': require('./img/highlight-3.webp') as string,
  'public/images/highlight-4.png': require('./img/highlight-4.webp') as string,
  'public/images/highlight1.png': require('./img/highlight1.webp') as string,
  'public/images/overlay.png': require('./img/overlay.webp') as string,
  'public/images/p-logo.png': require('./img/p-logo.webp') as string,
  'public/images/prize.png': require('./img/prize.webp') as string,
  'public/images/prize2.png': require('./img/prize2.webp') as string,
  'public/images/star.png': require('./img/star.webp') as string,
  'public/images/team1.png': require('./img/team1.webp') as string,
  'public/images/team2.png': require('./img/team2.webp') as string,
  'public/images/team3.png': require('./img/team3.webp') as string,
  'public/images/team4.png': require('./img/team4.webp') as string,
  'public/images/text.png': require('./img/text.webp') as string
};

const FFW2023_LOTTIE_MAP: Record<string, object> = {
  'public/json/Bag.json': require('./lottie/Bag.json'),
  'public/json/Coin.json': require('./lottie/Coin.json'),
  'public/json/Heart1.json': require('./lottie/Heart1.json'),
  'public/json/Heart2.json': require('./lottie/Heart2.json'),
  'public/json/Human.json': require('./lottie/Human.json'),
  'public/json/Leaf1.json': require('./lottie/Leaf1.json'),
  'public/json/Leaf2.json': require('./lottie/Leaf2.json'),
  'public/json/Red Circle.json': require('./lottie/Red-Circle.json'),
  'public/json/Star.json': require('./lottie/Star.json'),
  'public/json/White Speech.json': require('./lottie/White-Speech.json'),
  'public/json/Yellow Speech.json': require('./lottie/Yellow-Speech.json')
};

/** Resolve classic `public/images/...` path to bundled WebP URL. */
export function resolveFfw2023Image(classicPath: string): string {
  const normalized = classicPath.replace(/\\/g, '/');
  const url = FFW2023_IMAGE_MAP[normalized];

  if (!url) {
    console.warn('[Ffw2023] Missing bundled image for:', normalized);
    return normalized;
  }

  return url;
}

/** Bundled Lottie animation data for hero decorations. */
export function getFfw2023LottieAnimation(classicPath: string): object | undefined {
  const normalized = classicPath.replace(/\\/g, '/');
  return FFW2023_LOTTIE_MAP[normalized];
}

/** Resolve bundled image paths only (iCal uses SiteAssets — see ffw2023SiteAssetUrls). */
export function resolveFfw2023Asset(classicPath: string): string {
  const normalized = classicPath.replace(/\\/g, '/');

  if (normalized.indexOf('public/images/') === 0) {
    return resolveFfw2023Image(normalized);
  }

  return normalized;
}
