/* eslint-disable @typescript-eslint/no-var-requires */
/* Auto-generated by scripts/prepare-ffw2025-assets.mjs — do not edit manually */

const FFW2025_IMAGE_MAP: Record<string, string> = {
  'public/images/2024/clock.png': require('./img/2024/clock.webp') as string,
  'public/images/2024/Frame-dd.png': require('./img/2024/Frame-dd.webp') as string,
  'public/images/2024/location.png': require('./img/2024/location.webp') as string,
  'public/images/2024/play-icon.png': require('./img/2024/play-icon.webp') as string,
  'public/images/2025/BG_for_Microsite.png': require('./img/2025/BG_for_Microsite.webp') as string,
  'public/images/2025/logo.png': require('./img/2025/logo.webp') as string,
  'public/images/2025/MICROSITE.gif': require('./img/2025/MICROSITE.gif') as string
};

/** Resolve classic `public/images/...` path to bundled WebP (or GIF) URL. */
export function resolveFfw2025Image(classicPath: string): string {
  const normalized = classicPath.replace(/\\/g, '/');
  const url = FFW2025_IMAGE_MAP[normalized];

  if (!url) {
    console.warn('[Ffw2025] Missing bundled image for:', normalized);
    return normalized;
  }

  return url;
}
